CREATE TABLE IF NOT EXISTS "migrations" ("id" integer not null primary key autoincrement, "migration" varchar not null, "batch" integer not null);
CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE IF NOT EXISTS "users" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "password" varchar not null, "remember_token" varchar null, "created_at" datetime null, "updated_at" datetime null);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_resets" ("email" varchar not null, "token" varchar not null, "created_at" datetime null);
CREATE INDEX "password_resets_email_index" on "password_resets" ("email");
CREATE TABLE IF NOT EXISTS "abuse_reports" ("id" integer not null primary key autoincrement, "name" varchar null, "email" varchar null, "phone_number" varchar null, "location" varchar null, "description" text not null, "media_url" varchar not null, "created_at" datetime null, "updated_at" datetime null);
CREATE TABLE IF NOT EXISTS "admin_users" ("id" integer not null primary key autoincrement, "username" varchar not null, "password" varchar not null, "name" varchar not null, "avatar" varchar null, "remember_token" varchar null, "created_at" datetime null, "updated_at" datetime null);
CREATE UNIQUE INDEX "admin_users_username_unique" on "admin_users" ("username");
CREATE TABLE IF NOT EXISTS "admin_roles" ("id" integer not null primary key autoincrement, "name" varchar not null, "slug" varchar not null, "created_at" datetime null, "updated_at" datetime null);
CREATE UNIQUE INDEX "admin_roles_name_unique" on "admin_roles" ("name");
CREATE UNIQUE INDEX "admin_roles_slug_unique" on "admin_roles" ("slug");
CREATE TABLE IF NOT EXISTS "admin_permissions" ("id" integer not null primary key autoincrement, "name" varchar not null, "slug" varchar not null, "http_method" varchar null, "http_path" text null, "created_at" datetime null, "updated_at" datetime null);
CREATE UNIQUE INDEX "admin_permissions_name_unique" on "admin_permissions" ("name");
CREATE UNIQUE INDEX "admin_permissions_slug_unique" on "admin_permissions" ("slug");
CREATE TABLE IF NOT EXISTS "admin_menu" ("id" integer not null primary key autoincrement, "parent_id" integer not null default '0', "order" integer not null default '0', "title" varchar not null, "icon" varchar not null, "uri" varchar null, "permission" varchar null, "created_at" datetime null, "updated_at" datetime null);
CREATE TABLE IF NOT EXISTS "admin_role_users" ("role_id" integer not null, "user_id" integer not null, "created_at" datetime null, "updated_at" datetime null);
CREATE INDEX "admin_role_users_role_id_user_id_index" on "admin_role_users" ("role_id", "user_id");
CREATE TABLE IF NOT EXISTS "admin_role_permissions" ("role_id" integer not null, "permission_id" integer not null, "created_at" datetime null, "updated_at" datetime null);
CREATE INDEX "admin_role_permissions_role_id_permission_id_index" on "admin_role_permissions" ("role_id", "permission_id");
CREATE TABLE IF NOT EXISTS "admin_user_permissions" ("user_id" integer not null, "permission_id" integer not null, "created_at" datetime null, "updated_at" datetime null);
CREATE INDEX "admin_user_permissions_user_id_permission_id_index" on "admin_user_permissions" ("user_id", "permission_id");
CREATE TABLE IF NOT EXISTS "admin_role_menu" ("role_id" integer not null, "menu_id" integer not null, "created_at" datetime null, "updated_at" datetime null);
CREATE INDEX "admin_role_menu_role_id_menu_id_index" on "admin_role_menu" ("role_id", "menu_id");
CREATE TABLE IF NOT EXISTS "admin_operation_log" ("id" integer not null primary key autoincrement, "user_id" integer not null, "path" varchar not null, "method" varchar not null, "ip" varchar not null, "input" text not null, "created_at" datetime null, "updated_at" datetime null);
CREATE INDEX "admin_operation_log_user_id_index" on "admin_operation_log" ("user_id");
CREATE TABLE IF NOT EXISTS "contacts" ("id" integer not null primary key autoincrement, "name" varchar not null, "email" varchar not null, "subject" varchar not null, "message" text not null, "created_at" datetime null, "updated_at" datetime null);
CREATE TABLE IF NOT EXISTS "alarms" ("id" integer not null primary key autoincrement, "user_id" integer not null, "alarm" varchar not null, "created_at" datetime null, "updated_at" datetime null);
CREATE TABLE IF NOT EXISTS "timers" ("id" integer not null primary key autoincrement, "name" varchar not null, "start_time" varchar not null, "repeat_interval" varchar not null, "repeat_type" varchar not null, "active" tinyint(1) not null, "alarm_id" integer not null, "user_id" integer not null, "created_at" datetime null, "updated_at" datetime null);
